### PR TITLE
added bungee support

### PR DESCRIPTION
**Pull request by Peda1996**
Well,
I just added bungee support as I needed it for my server.
(i haven't tested starting without a config yet, but I think it will work, as the config is inside the resources.)

Enjoy

### CODE REVIEW

**Comment by Peda1996** [comment]
How can I create a pull request for the dev branch?

**Comment by spannerman79** [comment]
@JayWood needs to update the contributing docs, there _was_ a dev branch.  Unsure if a dev branch will come back to be used or not.

**Comment by JayWood** [comment]
Base updated to release branch, no more dev branches, mainly cuz it was just me so 🤷‍♂

**Comment by spannerman79** [comment]
The only thing I can see that is missing is documentation needed to send the required command to a specific server.  If indeed you are using bungee then 99% sure you would be running more then just two servers.

**Comment by Peda1996** [comment]
That shouldn't be a  big problem, as you can create different keys for different servers, therefore only use a different key for the bungee server, add the serverkey into your wordpress and you're ready to go.

**Comment by spannerman79** [comment]
True - although if you look at the number of issues that have been created that were either an issue with someones web server, or not reading/setting firewall excpetions if they use Cloudflare (even though its in both in wiki and also a note in issue creation), or using redirects (mentioned in FAQ wiki)... I can keep going on lol

So yes - documentation will need to be done if/when @JayWood accepts the PR.

**Comment by ethsmith** [comment]
@spannerman79 Did you try on 1.7.10 and it didn't work or did Jay just remove it from officially supported versions?

Also, if he tested this and it worked, why hasn't it been accepted?

**Comment by spannerman79** [comment]
> Did you try on 1.7.10 and it didn't work

Obvioulsy I have tried and yes it doesn't work on 1.7.10....
I wouldn't have stated otherwise.

**Comment by JayWood** [comment]
I've not tested it, that's why it's not been accepted yet. I am also working on other things, so there's that. Once i have the drive to circle back around and setup a testing environment for bungee I'll merge if all is well.

**Comment by JayWood** [comment]
I believe this was resolved with #256 - closing for now.

**Pull request closed without merging**
