### PR TITLE
Dev nightly

### PR DESCRIPTION
**Pull request by mcgamingf**
Hello, please help me

### CODE REVIEW

**Comment by spannerman79** [comment]
@mcgamingf you don't request help by asking in code commits.  Learn some Git/Github etiquette!

**Comment by mcgamingf** [comment]
Issue error: We cannot retrieve your account from the Mojang API. Try again later, or contact an administrator. Tell me what this means and how to solve the problem?

**Comment by ThisIzEthan** [comment]
Again, post an issue, not a PR

**Comment by JayWood** [comment]
@mcgamingf for christ sakes please open an ISSUE not a PR... https://github.com/WooMinecraft/WooMinecraft/issues

API's are out of my control, if it can't contact the Mojang API, check on [Mojang status](http://lmgtfy.com/?q=Mojang+API+Status) Green means good, yellow meh 🤷‍♂️ and red is bad.

**Pull request closed without merging**
