### PR TITLE
rest api fixes

### PR DESCRIPTION
**Pull request by jerzean**
>Pull requests should target **master**.
If your pull requests are not ready to be reviewed, please either label it as `WIP` or open a draft pull request.

## General Checks
Place an X in the boxes that you have completed for this pull request.

- [x] I have linked the ticket associated with this pull request.
- [x] I have fully tested my pull request.

## PR Notes
Add some general notes here about what your PR solves for.

ping command edit to test outgoing connections to any website
fix restapi link, make getsiteurl public (so i didnt have to add in the extra checks for rest api links)

### CODE REVIEW

**Review by JayWood — APPROVED** [review]

**Comment by JayWood** [comment]
@jerzean PR looks good, can you confirm this has been tested locally or add some screenshots of a local test?

**Comment by jerzean** [comment]
> @jerzean PR looks good, can you confirm this has been tested locally or add some screenshots of a local test?

havent tested locally, i dont have a website up atm, soon tho

**Comment by jerzean** [comment]
tested  it via my mc server and seems to be working, granted i dont have a website so it cant run orders but i didnt touch anything in that part of the plugin

**Comment by JayWood** [comment]
Got it thanks, I'll test tomorrow at some point and get this build out.

**Pull request merged**
