### PR TITLE
Would be useful to know if the HTTP response never happened

### PR DESCRIPTION
**Pull request by dordsor21**
//////////////////   
// PR's are NOT accepted on any branch other than dev-nightly.   
/////////////////

### CODE REVIEW

**Comment by TekkitCommando** [comment]
This is the plugin side, wouldn't it be better to use the server logger and not just throw a new exception.

**Comment by JayWood** [comment]
@TekkitCommando Check is built to throw an exception, and the runner is built to catch them - https://github.com/WooMinecraft/WooMinecraft/blob/master/src/main/java/com/plugish/woominecraft/Util/BukkitRunner.java#L19

**Comment by JayWood** [comment]
@dordsor21 - Have you considered turning on debug? - If so, all requests are logged now:

https://github.com/WooMinecraft/WooMinecraft/blob/master/src/main/java/com/plugish/woominecraft/Util/RcHttp.java#L74

**Comment by dordsor21** [comment]
Yeah, I realise that now, feel free to close the PR :)

**Pull request closed without merging**
