### PR TITLE
Corrected Player online check

### PR DESCRIPTION
**Pull request by FailPlayDE**
Issue: When processing donations to players who are not online, the plugin throws a NullPointer Exception and stops processing

Cause: in public boolean check(), players online status is requested by checking whether getServer().getPlayer("name").isOnline() returns true. According to the Bukkit documentation, getServer().getPlayer("name") returns a player (if online), otherwise NULL.
The correct way of telling if a player is online is to check if getServer().getPlayer("name") returns null.

BTW: getServer().getPlayerExact("name") is better than getServer().getPlayer("name"), because getPlayer() will also return a player if only a part of the name is matching

### CODE REVIEW

**Comment by TekkitCommando** [comment]
Why would getPlayer() return a player for a name that is only half correct?

**Comment by JayWood** [comment]
@FailPlayDE I think I see the issue, it's not the check itself, it's the lack of a check. Furthermore looking at your code it would appear the logic is backwards?

Take your snippet for example:
```if ( ! ( player == null ) ) {
     continue;
}```

However, this reads `if not true, then continue` the true being the `player==null` it's a nested logic statement yea?

I think what you were going for is:
```if ( player == null ) {
     continue;
}```
This reads `if player is null, continue`.

I do see the overall problem, and your fix is right there, just needs a logic fix I think. I'm still curious, wouldn't we still use `isOnline()` check? Docs only state it returns `a player object if one was found, null otherwise`

**Comment by FailPlayDE** [comment]
Hi,

@JayWood
Yes I see the fault in my logic, maybe I got the {continue;} wrong because i have not much experience with iterators.
Yours is right, the "!" has to be removed.

The isOnline() function on Players is a bit useless. It will always return true because the datatype Player always refers to a player who is online.
What you could do is using `getServer().getOfflinePlayer("name").isOnline()` instead, because OfflinePlayers *may* be online, too.
Though, getOfflinePlayer() will do a UUID lookup first (in the servers UUID cache or on the mojang servers) which takes a bit longer.

If you just want to check if a player is online, the `getPlayerExact("name") != null` check is an easy and effective solution.

@TekkitCommando
I think the getPlayer() method is a method to "look for" players. When you pass correct player names to it and there are no players with a similar name online, it will give you the player you are looking for.
But there are also some cases it will give you the wrong player. Using getPlayerExact() is just more secure.

**Comment by TekkitCommando** [comment]
@FailPlayDE Ah okay.

**Comment by JayWood** [comment]
@FailPlayDE So what you're saying is `Player player = Bukkit.getServer().getPlayerExact( playerName );` will only be non-null IF a player is online. And if I really want to check offline players I should use offlinePlayer object instead ( which I'm famliar with ).

If that's the case, I think the bukkit documentation should be a little clearer :smile:

**Comment by FailPlayDE** [comment]
@JayWood Yes, that's right.

The  bukkit documentation is like shit \o/ I prefer using the spigot documentation because it's the correct version of the bukkit docu.

**Pull request merged**
